version: 1
disable_existing_loggers: false

formatters:
  default:
    '()': labframe_api.logging_formatter.ColoredTimestampFormatter
    fmt: '%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red
  access:
    '()': labframe_api.logging_formatter.ColoredAccessFormatter
    fmt: '%(log_color)s%(asctime)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    log_colors:
      DEBUG: cyan
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red

handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [default]
    propagate: false
  uvicorn.access:
    level: INFO
    handlers: [access]
    propagate: false
  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: false

root:
  level: INFO
  handlers: [default]
